name: Test Scripts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-mock pymongo pydantic
        pip install -e .
    
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
    
    - name: Run repository_test.py
      run: |
        pytest tests/test_repository.py
    
    - name: Run finding_test.py
      run: |
        python tests/test_finding.py
